package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean loanAgeApproval;

	private java.lang.Double amount;

	private java.lang.Integer duration;

	private java.lang.Double monthlyRepayment;

	private Float interestRate;

	public Loan() {
	}

	public java.lang.Boolean getLoanAgeApproval() {
		return this.loanAgeApproval;
	}

	public void setLoanAgeApproval(java.lang.Boolean loanAgeApproval) {
		this.loanAgeApproval = loanAgeApproval;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.Integer getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Integer duration) {
		this.duration = duration;
	}

	public java.lang.Double getMonthlyRepayment() {
		return this.monthlyRepayment;
	}

	public void setMonthlyRepayment(java.lang.Double monthlyRepayment) {
		this.monthlyRepayment = monthlyRepayment;
	}

	public java.lang.Float getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(java.lang.Float interestRate) {
		this.interestRate = interestRate;
	}

	public Loan(java.lang.Boolean loanAgeApproval, java.lang.Double amount,
			java.lang.Integer duration, java.lang.Double monthlyRepayment,
			java.lang.Float interestRate) {
		this.loanAgeApproval = loanAgeApproval;
		this.amount = amount;
		this.duration = duration;
		this.monthlyRepayment = monthlyRepayment;
		this.interestRate = interestRate;
	}

}