package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double loanAmount;
	private java.lang.Double loanPct;

	public Loan() {
	}

	public java.lang.Double getLoanAmount() {
		return this.loanAmount;
	}

	public void setLoanAmount(java.lang.Double loanAmount) {
		this.loanAmount = loanAmount;
	}

	public java.lang.Double getLoanPct() {
		return this.loanPct;
	}

	public void setLoanPct(java.lang.Double loanPct) {
		this.loanPct = loanPct;
	}

	public Loan(java.lang.Double loanAmount, java.lang.Double loanPct) {
		this.loanAmount = loanAmount;
		this.loanPct = loanPct;
	}

}