package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Loan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean loanAgeApproval;

	private java.lang.Double amount;

	private java.lang.Integer duration;

	private java.lang.Double monthlyRepayment;

	private Double interestRate;

	private java.lang.Integer purchasePrice;

	private java.lang.Integer downPayment;

	private java.lang.Integer monthyIncome;

	public Loan() {
	}

	public java.lang.Boolean getLoanAgeApproval() {
		return this.loanAgeApproval;
	}

	public void setLoanAgeApproval(java.lang.Boolean loanAgeApproval) {
		this.loanAgeApproval = loanAgeApproval;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.Integer getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Integer duration) {
		this.duration = duration;
	}

	public java.lang.Double getMonthlyRepayment() {
		return this.monthlyRepayment;
	}

	public void setMonthlyRepayment(java.lang.Double monthlyRepayment) {
		this.monthlyRepayment = monthlyRepayment;
	}

	public java.lang.Double getInterestRate() {
		return this.interestRate;
	}

	public void setInterestRate(java.lang.Double interestRate) {
		this.interestRate = interestRate;
	}

	public java.lang.Integer getPurchasePrice() {
		return this.purchasePrice;
	}

	public void setPurchasePrice(java.lang.Integer purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	public java.lang.Integer getDownPayment() {
		return this.downPayment;
	}

	public void setDownPayment(java.lang.Integer downPayment) {
		this.downPayment = downPayment;
	}

	public java.lang.Integer getMonthyIncome() {
		return this.monthyIncome;
	}

	public void setMonthyIncome(java.lang.Integer monthyIncome) {
		this.monthyIncome = monthyIncome;
	}

	public Loan(java.lang.Boolean loanAgeApproval, java.lang.Double amount,
			java.lang.Integer duration, java.lang.Double monthlyRepayment,
			java.lang.Double interestRate, java.lang.Integer purchasePrice,
			java.lang.Integer downPayment, java.lang.Integer monthyIncome) {
		this.loanAgeApproval = loanAgeApproval;
		this.amount = amount;
		this.duration = duration;
		this.monthlyRepayment = monthlyRepayment;
		this.interestRate = interestRate;
		this.purchasePrice = purchasePrice;
		this.downPayment = downPayment;
		this.monthyIncome = monthyIncome;
	}

}